# Generated by Django 3.1.2 on 2020-10-25 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['instrument__name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=50)),
                ('data_source', models.CharField(choices=[('FI', 'Finki'), ('MS', 'Marketstack')], default='FI', max_length=2)),
                ('isin', models.CharField(max_length=12)),
                ('latest_price', models.FloatField(null=True)),
                ('latest_price_update_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('broker', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('fee', models.FloatField()),
                ('tax', models.FloatField()),
                ('fx_rate', models.FloatField()),
                ('fx_fee', models.FloatField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='tracker.holding')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentSplit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.FloatField()),
                ('date', models.DateField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.instrument')),
            ],
        ),
        migrations.AddField(
            model_name='holding',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.instrument'),
        ),
    ]
