# Generated by Django 3.1.2 on 2020-11-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.CharField(default='GBP', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrumentsplit',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='tracker.instrument'),
        ),
    ]
