# Generated by Django 2.1 on 2020-10-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201008_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='price',
            new_name='unit_price',
        ),
    ]
