# Generated by Django 2.1 on 2020-10-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20201008_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='trade',
            name='fx_fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='fx_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
