# Generated by Django 3.1.2 on 2020-11-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20201107_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='currency',
            new_name='payment_currency',
        ),
        migrations.AddField(
            model_name='trade',
            name='price_currency',
            field=models.CharField(default='GBP', max_length=3),
            preserve_default=False,
        ),
    ]
