# Generated by Django 2.1 on 2020-10-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20201008_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='broker',
            field=models.CharField(default='Freetrade', max_length=100),
            preserve_default=False,
        ),
    ]
