# Generated by Django 3.1.2 on 2020-11-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20201117_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='exchange',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
