# Generated by Django 2.1 on 2020-10-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_trade_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='exchange',
            field=models.CharField(default='LSE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='tax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
