# Generated by Django 3.1.2 on 2020-10-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20201017_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='data_source',
            field=models.CharField(choices=[('FI', 'Finki'), ('MS', 'Marketstack')], default='FI', max_length=2),
        ),
        migrations.AddField(
            model_name='holding',
            name='isin',
            field=models.CharField(default='x', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='holding',
            name='latest_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='latest_price_update_time',
            field=models.DateField(null=True),
        ),
    ]
