# Generated by Django 3.1.2 on 2020-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20201019_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=3)),
                ('exchange', models.CharField(max_length=50)),
                ('data_source', models.CharField(choices=[('FI', 'Finki'), ('MS', 'Marketstack')], default='FI', max_length=2)),
                ('isin', models.CharField(max_length=12)),
                ('latest_price', models.FloatField(null=True)),
                ('latest_price_update_time', models.DateField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
