# Generated by Django 3.1.2 on 2020-10-19 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='instrument',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='tracker.instrument'),
            preserve_default=False,
        ),
    ]
