# Generated by Django 3.1.2 on 2020-11-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20201117_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='category',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=20),
        ),
    ]
