# Generated by Django 3.1.2 on 2020-12-05 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_trade_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='fx_fee',
        ),
    ]
