# Generated by Django 3.1.2 on 2020-10-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_holding_instrument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['instrument']},
        ),
        migrations.RemoveField(
            model_name='holding',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='data_source',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='isin',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='latest_price',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='latest_price_update_time',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='name',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='symbol',
        ),
    ]
