# Generated by Django 3.1.2 on 2020-10-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20201019_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': ['instrument__name']},
        ),
    ]
