# Generated by Django 3.1.2 on 2020-10-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20201019_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={},
        ),
        migrations.AlterField(
            model_name='holding',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.instrument'),
        ),
    ]
