# Generated by Django 3.1.2 on 2021-01-16 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20201208_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holding',
            options={'ordering': [django.db.models.functions.text.Lower('instrument__name')]},
        ),
        migrations.AlterField(
            model_name='trade',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='tracker.holding'),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('broker', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='tracker.holding')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
