# Generated by Django 3.1.2 on 2020-10-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20201020_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='latest_price_update_time',
            field=models.DateTimeField(null=True),
        ),
    ]
