# Generated by Django 3.1.2 on 2021-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20210116_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='t212_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
