# Generated by Django 3.1.2 on 2021-02-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20210221_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividend',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
    ]
