/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://l3i5am4hwvapfiuoopvuiyxnjy.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-v3obhlc6cfc3je5nml5nejuvz4",
    "aws_cognito_identity_pool_id": "eu-west-2:c326fdbc-5fb6-4582-84e2-3d5f3bcbca85",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_1qCmuz2rk",
    "aws_user_pools_web_client_id": "10de8gjlstdi2572bsapoasvrr",
    "oauth": {}
};


export default awsmobile;
